### ISSUE TITLE
import auth from youwave to sda mod

### ISSUE THREAD

**Issue by cromwell221** [hyt47/SteamDesktopAuthenticator-Mod-47#1]
Hello. Thank you for your good work!
Is there any way to import steam authenticator to sda mod from my youwave android emulator?
I saw that topic at FAQ about Android import but it won't work for the emulator obviously.
I got this at Root Explorer: 
![dyzas6b](https://cloud.githubusercontent.com/assets/16307900/14101399/e105a6e4-f59c-11e5-8319-9fb7dcf7a0d9.png)

**Comment by cromwell221** [comment]
There's Steamguard-7656**************\* file at com.valvesoftware.android.steam.community\files\
Maybe it's the key? What should I do? Help me please
PS I have exported all the 'com.valvesoftware.android.steam.community' directory from Youwave to my WinXP desktop already.

**Comment by hyt47** [comment]
I'm looking into your problem...

**Comment by hyt47** [comment]
**Use this tutorial:** https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47/wiki/Manually-import-your-Steam-Account-from-Android

**Comment by cromwell221** [comment]
It worked. Thank you a lot!
