### ISSUE TITLE
Cant download or rate drops to zero

### ISSUE THREAD

**Issue by Wrascon** [hyt47/SteamDesktopAuthenticator-Mod-47#10]
Chrome writes that the file will be downloaded in an hour, but in fact it's been more than 3, and 5 times behind the download, which produces an error and download was interrupted by error. I have no problem with [my internet connection](http://www.speedtest.net/my-result/5413597177), but the download speed is [0](http://image.prntscr.com/image/1d3d0f949998476c8afe7bd819062f82.png), then [3.4](http://image.prntscr.com/image/8e05e499a3b44e309845d4d88ccb9250.png), then [canceled](http://image.prntscr.com/image/e87ef56158f14cc192df1079e8c6f767.png) witn error. Recently I re-downloaded the ASF, the rate was similar, but at least I was able to download it without any errors. VPN during the download was off and I just can not begin to use your creation. Another browser does not help, I do not know how to fix it. I hope I will be able to test your program in the future.

**Comment by hyt47** [comment]
I don't know why u have this problem, for me it works fine.
Try these links:
[SDA.47.Full.Release.rar - zippyshare.com](http://www28.zippyshare.com/v/BDvpklUV/file.html)
[SDA.47.Full.Source.rar - zippyshare.com](http://www114.zippyshare.com/v/rU5y4KKO/file.html)
