### ISSUE TITLE
Change your button text

### ISSUE THREAD

**Issue by ghost** [hyt47/SteamDesktopAuthenticator-Mod-47#13]
I just found you mod, It's a cool mod but I think this test is better

"View Trade Confirmation in Browser" change to "Vicw Confirmation in Browser"
and
"View Trade Confirmation List" change to "Vicw Confirmation List"
because it is all confirmation incl. market-accept and trade-accept

Thanks

**Comment by ghost** [comment]
Check all accounts confirmation isn't work

**Comment by ghost** [comment]
When enable auto confirm at startup delay time IT WILL NOT CHECK FOR ALL CONFIRMATION

**Comment by ghost** [comment]
*When enable auto confirm at startup delay time IT WILL NOT CHECK FOR ALL CONFIRMATION
When time is counting down when start new program, It's no check for all confirmation

**Comment by hyt47** [comment]
I'll check tomorrow, If you can't see your confirmations in the browser, login again to refresh the session

**Comment by hyt47** [comment]
I-ll change View Confirmation List text in the next update

**Comment by hyt47** [comment]
@pohuiusemail4741  Thx for info! The app was fixed and the button text changed.
