### ISSUE TITLE
Stop abusing GitHub!

### ISSUE THREAD

**Issue by MikeLund** [hyt47/SteamDesktopAuthenticator-Mod-47#16]
Continuing from https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47/issues/11 which was closed...

What kind of nonsense is "don't have time to update the files" supposed to mean? You just install Git, select the folder and repo, and click commit. There's even a GUI client, it can't be easier. https://desktop.github.com/

So there really is no excuse. You can still offer your binaries, just do it without the source-code bundled in it. Put the source-code on the VCS (GitHub) properly as it should be.

**Comment by hyt47** [comment]
Done! Enjoy :)
