### ISSUE TITLE
Error: Invalid length for a Base-64  char array or string

### ISSUE THREAD

**Issue by Rezi727** [hyt47/SteamDesktopAuthenticator-Mod-47#17]
http://pastebin.com/iuJFAnRz

**Comment by hyt47** [comment]
Hello! You tried to import from android and u got that error ?

**Comment by Rezi727** [comment]
Yea, I import account from android using: "Manually import your Steam Account from Android" guide.

**Comment by hyt47** [comment]
you made a mistake somewhere

**Comment by Rezi727** [comment]
Thanks now app is works! But now I have a new problem :(  
https://gyazo.com/50c5d8bc7cdcb665b5a1db613a151fed

**Comment by hyt47** [comment]
try:
1. Force session refresh
2. Login again

**Comment by Rezi727** [comment]
This is not working for me. Also when i open "view trade confirmation in browser" i got this https://gyazo.com/d76dad08ff6a8f43d250ca8891cf569f. Though codes on my android and codes in app equal to 100%. Maybe a problem that I use Moscow time (GMT+3) ?

**Comment by hyt47** [comment]
If the steam Authenticator is working on your Android device it should work on the SDA app.  I don't know how to help u sry.

**Comment by Rezi727** [comment]
I resolve a problem. Remove Steam Authentication on my android and after that just setup a new account in SDA.

**Comment by hyt47** [comment]
Thx for info

**Comment by renanrkk** [comment]
Hello I open my id.mafile and is encrypted as I shot this encryption

**Comment by hyt47** [comment]
SDA47 will recreate the json file at startup, if the file doesn't exist
