### ISSUE TITLE
I always have no confirmations

### ISSUE THREAD

**Issue by Wrascon** [hyt47/SteamDesktopAuthenticator-Mod-47#18]
Nothing to confirm
You don't have anything to confirm right now.

Thats what i always see in View Сonfirmations. Auto-confirm not helping. Still have this problem in 1.0.7.5 after i install 1.0.6.1 and import it from my android.
Other accounts work alright

**Comment by hyt47** [comment]
Hi! There are a couple of things u can try: 
1 "Force session refresh"
2 "Login again"
3 Import your account manually (or verify the existing content from .maFile)
Do a backup of the .maFile first
https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47/wiki/Manually-import-your-Steam-Account-from-Android
