### ISSUE TITLE
Login Token

### ISSUE THREAD

**Issue by swerux** [hyt47/SteamDesktopAuthenticator-Mod-47#21]
Hi
How can i get login token if i have all decrypted data (shared_secret, serial_number,revocation_code etc) in console app? Pls help in code
```
static private void loadAccountInfo()
        {
            if (currentAccount != null && steamTime != 0)
            {
                Console.WriteLine(currentAccount.GenerateSteamGuardCodeForTime(steamTime));
            }
        }
```

`{"shared_secret":"2LlAec6ZQ**********3Jg=","serial_number":"13178066****71216","revocation_code":"R****","uri":"otpauth://totp/Steam:nickname?secret=3C******XATGW4******MPXEY&issuer=Steam","server_time":1478105991,"account_name":"nickname","token_gid":"c******2**3","identity_secret":"/v****M******y8****lu8****=","secret_1":"q6INptloowe*******x3A4Q=","status":1,"device_id":"android:7841fc03-51f6-fc03-fc03-fc0351f6cdad","fully_enrolled":true,"Session":{"SessionID":"188dfa*****6ac6697","SteamLogin":"76561**************%7C%7CC3E69B1**************94DFF3BFBF5BC1****20","SteamLoginSecure":"765611********%7C%7CBFBDB333501C8280CKK*****88EF6F990D2024","WebCookie":"A1B66**********03090042F8456F97622B6F4D","OAuthToken":"41f187************************","SteamID":76561******}}`

**Comment by hyt47** [comment]
Using the loop that checks for confirmations (in MainForm.cs), u can add there after

```
                // Check 
                //////////////////////////
                foreach (var acc in CheckAccounts) {
                    if (acc == null) { return; }

                    await UpdateCurrentSession_ForBg(acc);
```

add

```
                    // info Show Token
                    var SDAToken = acc.GenerateSteamGuardCodeForTime(steamTime);
                    Program.ConsoleForm_Update.SetConsoleText("Token " + acc.AccountName + " : " + SDAToken, "ConsoleStatus_Info");
```

Depending of what u need you can create your own function that has a similar loop
