### ISSUE TITLE
Authenticator Wont Launch On Linux

### ISSUE THREAD

**Issue by SomeRandomShiit** [hyt47/SteamDesktopAuthenticator-Mod-47#24]
I tried through launching the application and terminal, nothing. Please help if I'm doing something wrong

**Comment by jackqc** [comment]
Just seen your comment. May I ask which version of the authenticator you're using and which version of mono? I've got 1.0.7.6 here (still haven't upgraded to the latest one it seems) and  mono 5.0.1.1 on Linux Mint 17.3 ... which works very well.
