### ISSUE TITLE
Bugs on 1.0.7.7

### ISSUE THREAD

**Issue by ghost** [hyt47/SteamDesktopAuthenticator-Mod-47#25]
I'm using SDA 47 with 11 and it always fail to refrash seesion. I think this is the problem
1.) The program always sync time with server (Aligning time with steam)
2.) Duration check between account are very fast, When "Check all accounts for confirmations" is marked. You should have delay between perform check 1-2 sec. 
3.) from 2.) I use this program to make trade cards and marketing, I always use  "Auto-confirm Trade/ Market : yes"

Thanks, :)

**Comment by ghost** [comment]
4) .I had to try on WinAuth, It aligning time with steam and the first time I open the program. But then 3-5 min the Steam Guard Code is not work, I should re-open the program the make the new sync.
I suggest you to make your SDA 47 sync the frist time when open or selected account. And have sync button to make new "Aligning time with steam"
4.1) Make button in "Settings" named "Auto alinging Time with steam" interval xx second
4.2) Make button in "File" with "Force all refrash session" to refrash session for all accounts with 1-click ( Sure, don't forget to delay between accounts :] )


Sincerely,
Pohui

**Comment by hyt47** [comment]
New fix soon, I hope it will help.

**Comment by hyt47** [comment]
Thx for info !

**Comment by hyt47** [comment]
For now I added Delay Session Refresh in settings & a button File > Refresh Session for All Accounts,

**Comment by ghost** [comment]
Thanks :)🏆🏆🏆

**Comment by ghost** [comment]
Thanks :)🏆🏆🏆
