### ISSUE TITLE
Can't confirm trades

### ISSUE THREAD

**Issue by KeeperOfMonsters** [hyt47/SteamDesktopAuthenticator-Mod-47#28]
I was using latest version of SDA and up until yesterday everything was working fine. Then all of a sudden I can't confirm trades - just getting blank white window. Tried forcing-refresh, logging in, removing and installing  SDA  again (with backing up and copying .maFile), restarting computer - nothing helps.
Then I stumbled upon this program, but after deleting SDA, installing Mod 47, importing old maFile - I still have this problem.
Authenticator part works OK - codes displayed and working, I can log in Steam client and through browser just fine, but I can't confirm any trades.
Force session refresh returns error (failed... try again soon).
Login again - "Error logging in: Steam returned GeneralFailure."
And again - restarting program and computer doesn't help.
Is there any way to fix it without disabling authenticator and re-enablimg it? I don't want to have a hold for 15 days...
P.S. I haven't change anything on my computer before it happens.
P.P.S. I have another version of SDA running on old notebook - and that one working just fine, even though it wasn't updated in a year at least. I use it for couple of farming accounts and have no problems with trades there. This newer version on new computer used only for my main account (and that's the only authenticator program used for this account).

**Comment by hyt47** [comment]
New fix soon, I hope it will help. It worked for me to confirm using the Browser...
