### ISSUE TITLE
error converting null value

### ISSUE THREAD

**Issue by skyborgff** [hyt47/SteamDesktopAuthenticator-Mod-47#6]
http://pastebin.com/cT6Q0Bt9

**Comment by hyt47** [comment]
JsonSerializationException = your maFile is not valid, a value that needs to be a number is null

**Comment by skyborgff** [comment]
but i was using the option to import from a android device.Isn't it supposed to be valid?
I worked around and manualy made a .maFile

**Comment by hyt47** [comment]
yeah it should have extracted the full data, I guess there's a bug somewhere... I extracted 2 accounts using this app and it worked for me, so the bug might appear only for a few people,  that have the data different for a variable...
