### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by skyborgff** [hyt47/SteamDesktopAuthenticator-Mod-47#9]
Hi, i have 2 accounts and im am constantly switching between them. is there any way to auto fill the code that is asked when we log in?
I am using this https://github.com/W3D3/SteamAccountSwitcher/releases/tag/1.1 to switch between them. 
Is it possible to only allow auto accept trade/market to one account when you have two configurated ?
Thanks for the good work.

**Comment by hyt47** [comment]
1. auto fill - no
2. allow auto accept trade/market to only one account - no, but you can use 2 SDA apps, 1 account per app
